mod login;
mod logout;
mod register;
mod register_as_admin;
mod validate;
pub use login::{login, Data as LoginData};
pub use logout::*;
pub use register::{register, Data as RegisterData};
pub use register_as_admin::{register_as_admin, Data as RegisterAsAdminData};
pub use validate::*;