CREATE TABLE "garden_planner"."Worker" (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	user_id BIGINT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	FOREIGN KEY (user_id) REFERENCES "garden_planner"."User" (id) MATCH FULL ON DELETE CASCADE
);